package dropnext.lib.jdbi.fake

import java.math.BigDecimal
import java.sql.Array as SqlArray
import java.sql.Blob
import java.sql.Clob
import java.sql.Date
import java.sql.NClob
import java.sql.Ref
import java.sql.ResultSet
import java.sql.RowId
import java.sql.SQLWarning
import java.sql.SQLXML
import java.sql.Statement
import java.sql.Time
import java.sql.Timestamp


/** Base implementation for fake ResultSet with common behavior. */
abstract class BaseFakeResultSet : ResultSet {
  protected var lastWasNull = false

  override fun wasNull(): Boolean = lastWasNull

  // All navigation and update methods throw UnsupportedOperationException
  override fun next(): Boolean = throw UnsupportedOperationException("Not implemented in fake")
  override fun close() = throw UnsupportedOperationException("Not implemented in fake")
  override fun getWarnings(): SQLWarning = throw UnsupportedOperationException("Not implemented in fake")
  override fun clearWarnings() = throw UnsupportedOperationException("Not implemented in fake")
  override fun getCursorName(): String = throw UnsupportedOperationException("Not implemented in fake")
  override fun isBeforeFirst(): Boolean = throw UnsupportedOperationException("Not implemented in fake")
  override fun isAfterLast(): Boolean = throw UnsupportedOperationException("Not implemented in fake")
  override fun isFirst(): Boolean = throw UnsupportedOperationException("Not implemented in fake")
  override fun isLast(): Boolean = throw UnsupportedOperationException("Not implemented in fake")
  override fun beforeFirst() = throw UnsupportedOperationException("Not implemented in fake")
  override fun afterLast() = throw UnsupportedOperationException("Not implemented in fake")
  override fun first(): Boolean = throw UnsupportedOperationException("Not implemented in fake")
  override fun last(): Boolean = throw UnsupportedOperationException("Not implemented in fake")
  override fun getRow(): Int = throw UnsupportedOperationException("Not implemented in fake")
  override fun absolute(row: Int): Boolean = throw UnsupportedOperationException("Not implemented in fake")
  override fun relative(rows: Int): Boolean = throw UnsupportedOperationException("Not implemented in fake")
  override fun previous(): Boolean = throw UnsupportedOperationException("Not implemented in fake")
  override fun setFetchDirection(direction: Int) = throw UnsupportedOperationException("Not implemented in fake")
  override fun getFetchDirection(): Int = throw UnsupportedOperationException("Not implemented in fake")
  override fun setFetchSize(rows: Int) = throw UnsupportedOperationException("Not implemented in fake")
  override fun getFetchSize(): Int = throw UnsupportedOperationException("Not implemented in fake")
  override fun getType(): Int = throw UnsupportedOperationException("Not implemented in fake")
  override fun getConcurrency(): Int = throw UnsupportedOperationException("Not implemented in fake")
  override fun rowUpdated(): Boolean = throw UnsupportedOperationException("Not implemented in fake")
  override fun rowInserted(): Boolean = throw UnsupportedOperationException("Not implemented in fake")
  override fun rowDeleted(): Boolean = throw UnsupportedOperationException("Not implemented in fake")

  // Update methods
  override fun updateNull(columnIndex: Int) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateBoolean(columnIndex: Int, x: Boolean) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateByte(columnIndex: Int, x: Byte) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateShort(columnIndex: Int, x: Short) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateInt(columnIndex: Int, x: Int) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateLong(columnIndex: Int, x: Long) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateFloat(columnIndex: Int, x: Float) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateDouble(columnIndex: Int, x: Double) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateBigDecimal(columnIndex: Int, x: BigDecimal?) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateString(columnIndex: Int, x: String?) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateBytes(columnIndex: Int, x: ByteArray?) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateDate(columnIndex: Int, x: Date?) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateTime(columnIndex: Int, x: Time?) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateTimestamp(columnIndex: Int, x: Timestamp?) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateAsciiStream(columnIndex: Int, x: java.io.InputStream?, length: Int) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateBinaryStream(columnIndex: Int, x: java.io.InputStream?, length: Int) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateCharacterStream(columnIndex: Int, x: java.io.Reader?, length: Int) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateObject(columnIndex: Int, x: Any?, scaleOrLength: Int) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateObject(columnIndex: Int, x: Any?) = throw UnsupportedOperationException("Not implemented in fake")

  // Update by column label
  override fun updateNull(columnLabel: String?) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateBoolean(columnLabel: String?, x: Boolean) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateByte(columnLabel: String?, x: Byte) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateShort(columnLabel: String?, x: Short) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateInt(columnLabel: String?, x: Int) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateLong(columnLabel: String?, x: Long) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateFloat(columnLabel: String?, x: Float) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateDouble(columnLabel: String?, x: Double) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateBigDecimal(columnLabel: String?, x: BigDecimal?) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateString(columnLabel: String?, x: String?) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateBytes(columnLabel: String?, x: ByteArray?) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateDate(columnLabel: String?, x: Date?) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateTime(columnLabel: String?, x: Time?) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateTimestamp(columnLabel: String?, x: Timestamp?) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateAsciiStream(columnLabel: String?, x: java.io.InputStream?, length: Int) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateBinaryStream(columnLabel: String?, x: java.io.InputStream?, length: Int) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateCharacterStream(columnLabel: String?, reader: java.io.Reader?, length: Int) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateObject(columnLabel: String?, x: Any?, scaleOrLength: Int) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateObject(columnLabel: String?, x: Any?) = throw UnsupportedOperationException("Not implemented in fake")

  // Row manipulation
  override fun insertRow() = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateRow() = throw UnsupportedOperationException("Not implemented in fake")
  override fun deleteRow() = throw UnsupportedOperationException("Not implemented in fake")
  override fun refreshRow() = throw UnsupportedOperationException("Not implemented in fake")
  override fun cancelRowUpdates() = throw UnsupportedOperationException("Not implemented in fake")
  override fun moveToInsertRow() = throw UnsupportedOperationException("Not implemented in fake")
  override fun moveToCurrentRow() = throw UnsupportedOperationException("Not implemented in fake")

  // Other getters
  override fun getStatement(): Statement = throw UnsupportedOperationException("Not implemented in fake")
  override fun getRef(columnIndex: Int): Ref = throw UnsupportedOperationException("Not implemented in fake")
  override fun getBlob(columnIndex: Int): Blob = throw UnsupportedOperationException("Not implemented in fake")
  override fun getClob(columnIndex: Int): Clob = throw UnsupportedOperationException("Not implemented in fake")
  override fun getRef(columnLabel: String?): Ref = throw UnsupportedOperationException("Not implemented in fake")
  override fun getBlob(columnLabel: String?): Blob = throw UnsupportedOperationException("Not implemented in fake")
  override fun getClob(columnLabel: String?): Clob = throw UnsupportedOperationException("Not implemented in fake")
  override fun getArray(columnLabel: String?): SqlArray = throw UnsupportedOperationException("Not implemented in fake")
  override fun getDate(columnIndex: Int, cal: java.util.Calendar?): Date = throw UnsupportedOperationException("Not implemented in fake")
  override fun getDate(columnLabel: String?, cal: java.util.Calendar?): Date = throw UnsupportedOperationException("Not implemented in fake")
  override fun getTime(columnIndex: Int, cal: java.util.Calendar?): Time = throw UnsupportedOperationException("Not implemented in fake")
  override fun getTime(columnLabel: String?, cal: java.util.Calendar?): Time = throw UnsupportedOperationException("Not implemented in fake")
  override fun getTimestamp(columnIndex: Int, cal: java.util.Calendar?): Timestamp = throw UnsupportedOperationException("Not implemented in fake")
  override fun getTimestamp(columnLabel: String?, cal: java.util.Calendar?): Timestamp = throw UnsupportedOperationException("Not implemented in fake")
  override fun getURL(columnIndex: Int): java.net.URL = throw UnsupportedOperationException("Not implemented in fake")
  override fun getURL(columnLabel: String?): java.net.URL = throw UnsupportedOperationException("Not implemented in fake")

  // Additional update methods
  override fun updateRef(columnIndex: Int, x: Ref?) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateRef(columnLabel: String?, x: Ref?) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateBlob(columnIndex: Int, x: Blob?) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateBlob(columnLabel: String?, x: Blob?) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateClob(columnIndex: Int, x: Clob?) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateClob(columnLabel: String?, x: Clob?) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateArray(columnIndex: Int, x: SqlArray?) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateArray(columnLabel: String?, x: SqlArray?) = throw UnsupportedOperationException("Not implemented in fake")

  // JDBC 4.0 methods
  override fun getRowId(columnIndex: Int): RowId = throw UnsupportedOperationException("Not implemented in fake")
  override fun getRowId(columnLabel: String?): RowId = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateRowId(columnIndex: Int, x: RowId?) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateRowId(columnLabel: String?, x: RowId?) = throw UnsupportedOperationException("Not implemented in fake")
  override fun getHoldability(): Int = throw UnsupportedOperationException("Not implemented in fake")
  override fun isClosed(): Boolean = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateNString(columnIndex: Int, nString: String?) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateNString(columnLabel: String?, nString: String?) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateNClob(columnIndex: Int, nClob: NClob?) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateNClob(columnLabel: String?, nClob: NClob?) = throw UnsupportedOperationException("Not implemented in fake")
  override fun getNClob(columnIndex: Int): NClob = throw UnsupportedOperationException("Not implemented in fake")
  override fun getNClob(columnLabel: String?): NClob = throw UnsupportedOperationException("Not implemented in fake")
  override fun getSQLXML(columnIndex: Int): SQLXML = throw UnsupportedOperationException("Not implemented in fake")
  override fun getSQLXML(columnLabel: String?): SQLXML = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateSQLXML(columnIndex: Int, xmlObject: SQLXML?) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateSQLXML(columnLabel: String?, xmlObject: SQLXML?) = throw UnsupportedOperationException("Not implemented in fake")
  override fun getNString(columnIndex: Int): String = throw UnsupportedOperationException("Not implemented in fake")
  override fun getNString(columnLabel: String?): String = throw UnsupportedOperationException("Not implemented in fake")
  override fun getNCharacterStream(columnIndex: Int): java.io.Reader = throw UnsupportedOperationException("Not implemented in fake")
  override fun getNCharacterStream(columnLabel: String?): java.io.Reader = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateNCharacterStream(columnIndex: Int, x: java.io.Reader?, length: Long) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateNCharacterStream(columnLabel: String?, reader: java.io.Reader?, length: Long) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateAsciiStream(columnIndex: Int, x: java.io.InputStream?, length: Long) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateBinaryStream(columnIndex: Int, x: java.io.InputStream?, length: Long) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateCharacterStream(columnIndex: Int, x: java.io.Reader?, length: Long) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateAsciiStream(columnLabel: String?, x: java.io.InputStream?, length: Long) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateBinaryStream(columnLabel: String?, x: java.io.InputStream?, length: Long) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateCharacterStream(columnLabel: String?, reader: java.io.Reader?, length: Long) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateBlob(columnIndex: Int, inputStream: java.io.InputStream?, length: Long) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateBlob(columnLabel: String?, inputStream: java.io.InputStream?, length: Long) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateClob(columnIndex: Int, reader: java.io.Reader?, length: Long) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateClob(columnLabel: String?, reader: java.io.Reader?, length: Long) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateNClob(columnIndex: Int, reader: java.io.Reader?, length: Long) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateNClob(columnLabel: String?, reader: java.io.Reader?, length: Long) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateNCharacterStream(columnIndex: Int, x: java.io.Reader?) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateNCharacterStream(columnLabel: String?, reader: java.io.Reader?) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateAsciiStream(columnIndex: Int, x: java.io.InputStream?) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateBinaryStream(columnIndex: Int, x: java.io.InputStream?) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateCharacterStream(columnIndex: Int, x: java.io.Reader?) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateAsciiStream(columnLabel: String?, x: java.io.InputStream?) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateBinaryStream(columnLabel: String?, x: java.io.InputStream?) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateCharacterStream(columnLabel: String?, reader: java.io.Reader?) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateBlob(columnIndex: Int, inputStream: java.io.InputStream?) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateBlob(columnLabel: String?, inputStream: java.io.InputStream?) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateClob(columnIndex: Int, reader: java.io.Reader?) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateClob(columnLabel: String?, reader: java.io.Reader?) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateNClob(columnIndex: Int, reader: java.io.Reader?) = throw UnsupportedOperationException("Not implemented in fake")
  override fun updateNClob(columnLabel: String?, reader: java.io.Reader?) = throw UnsupportedOperationException("Not implemented in fake")

  // Get by label methods
  override fun getObject(columnLabel: String?, map: MutableMap<String, Class<*>>): Any = throw UnsupportedOperationException("Not implemented in fake")
  override fun <T : Any?> getObject(columnLabel: String?, type: Class<T>?): T = throw UnsupportedOperationException("Not implemented in fake")
  override fun <T : Any?> unwrap(iface: Class<T>?): T = throw UnsupportedOperationException("Not implemented in fake")
  override fun isWrapperFor(iface: Class<*>?): Boolean = throw UnsupportedOperationException("Not implemented in fake")
  override fun findColumn(columnLabel: String?): Int = throw UnsupportedOperationException("Not implemented in fake")
  override fun getCharacterStream(columnIndex: Int): java.io.Reader = throw UnsupportedOperationException("Not implemented in fake")
  override fun getCharacterStream(columnLabel: String?): java.io.Reader = throw UnsupportedOperationException("Not implemented in fake")
  override fun getBigDecimal(columnIndex: Int): BigDecimal = throw UnsupportedOperationException("Not implemented in fake")
  override fun getBigDecimal(columnLabel: String?): BigDecimal = throw UnsupportedOperationException("Not implemented in fake")
  override fun getBytes(columnIndex: Int): ByteArray = throw UnsupportedOperationException("Not implemented in fake")
  override fun getBytes(columnLabel: String?): ByteArray = throw UnsupportedOperationException("Not implemented in fake")
  override fun getDate(columnIndex: Int): Date = throw UnsupportedOperationException("Not implemented in fake")
  override fun getDate(columnLabel: String?): Date = throw UnsupportedOperationException("Not implemented in fake")
  override fun getTime(columnIndex: Int): Time = throw UnsupportedOperationException("Not implemented in fake")
  override fun getTime(columnLabel: String?): Time = throw UnsupportedOperationException("Not implemented in fake")
  override fun getTimestamp(columnLabel: String?): Timestamp = throw UnsupportedOperationException("Not implemented in fake")
  override fun getAsciiStream(columnIndex: Int): java.io.InputStream = throw UnsupportedOperationException("Not implemented in fake")
  @Deprecated("Deprecated in Java")
  override fun getUnicodeStream(columnIndex: Int): java.io.InputStream = throw UnsupportedOperationException("Not implemented in fake")
  override fun getBinaryStream(columnIndex: Int): java.io.InputStream = throw UnsupportedOperationException("Not implemented in fake")
  override fun getString(columnLabel: String?): String = throw UnsupportedOperationException("Not implemented in fake")
  override fun getBoolean(columnLabel: String?): Boolean = throw UnsupportedOperationException("Not implemented in fake")
  override fun getByte(columnLabel: String?): Byte = throw UnsupportedOperationException("Not implemented in fake")
  override fun getShort(columnLabel: String?): Short = throw UnsupportedOperationException("Not implemented in fake")
  override fun getInt(columnLabel: String?): Int = throw UnsupportedOperationException("Not implemented in fake")
  override fun getLong(columnLabel: String?): Long = throw UnsupportedOperationException("Not implemented in fake")
  override fun getFloat(columnLabel: String?): Float = throw UnsupportedOperationException("Not implemented in fake")
  override fun getDouble(columnLabel: String?): Double = throw UnsupportedOperationException("Not implemented in fake")
  @Deprecated("Deprecated in Java")
  override fun getBigDecimal(columnIndex: Int, scale: Int): BigDecimal = throw UnsupportedOperationException("Not implemented in fake")
  @Deprecated("Deprecated in Java")
  override fun getBigDecimal(columnLabel: String?, scale: Int): BigDecimal = throw UnsupportedOperationException("Not implemented in fake")
  override fun getAsciiStream(columnLabel: String?): java.io.InputStream = throw UnsupportedOperationException("Not implemented in fake")
  @Deprecated("Deprecated in Java")
  override fun getUnicodeStream(columnLabel: String?): java.io.InputStream = throw UnsupportedOperationException("Not implemented in fake")
  override fun getBinaryStream(columnLabel: String?): java.io.InputStream = throw UnsupportedOperationException("Not implemented in fake")
  override fun getObject(columnLabel: String?): Any = throw UnsupportedOperationException("Not implemented in fake")
  override fun getObject(columnIndex: Int, map: MutableMap<String, Class<*>>): Any = throw UnsupportedOperationException("Not implemented in fake")
}
